# ESTRUCTURAS DE DATOS

## LISTAS

Array, son contenedores que permiten almacenar una colección de datos.

In [1]:
L1 = [] #Lista vacia,se determina por los corchetes cuadrados

In [2]:
L2 = ["a","e","i","o","u"]#Lista con valores inicializados

In [3]:
L4 = ["a",1,3.4,"Jhon Cruz", True]#Lista Hetorogenea

In [4]:
L5 = [0]*10 # Para crear una lista de 10 posiciones

In [5]:
L5

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [8]:
L4[0]#Listas empiezan en python desde cero,numero cero como natural y empieza desde cero

'a'

In [9]:
L5[4] = 3.1415#Acceder a una posicion y modificar el dato
L5

[0, 0, 0, 0, 3.1415, 0, 0, 0, 0, 0]

In [11]:
L5[13] = 8 # error por que tu lista solo tiene diez posiciones

IndexError: list assignment index out of range

In [12]:
L4[0:2]#Para acceder a un rango especifico, posicion ultima menos 1

['a', 1]

In [13]:
L5[1:4]=[1,2,3]#Para modificar un rango especifico
L5

[0, 1, 2, 3, 3.1415, 0, 0, 0, 0, 0]

In [14]:
L5.append(8)#Para añadir un numero a la ultima posicion
L5

[0, 1, 2, 3, 3.1415, 0, 0, 0, 0, 0, 8]

In [15]:
L5.remove(3)#elimina el numero 3 dentro la lista, el primero que encuentre
L5

[0, 1, 2, 3.1415, 0, 0, 0, 0, 0, 8]

In [16]:
L5.remove(0)#elimina elprimer 0 que encuentre

In [17]:
L5

[1, 2, 3.1415, 0, 0, 0, 0, 0, 8]

In [18]:
L5.remove(0)
L5

[1, 2, 3.1415, 0, 0, 0, 0, 8]

In [19]:
L5.reverse()#Voltea la lista
L5

[8, 0, 0, 0, 0, 3.1415, 2, 1]

In [21]:
L5.count(0)#Para saber cuantos 0 existen e la lista

4

In [22]:
L5.index(3.1415)#Que posicion se encuentra el numero 3.1415

5

In [23]:
len(L5)#Longitud de la lista,contiene 8 elementos

8

In [24]:
L = [1,2,3,4,5,6]
L[1::2]#acceder de dos en dos, en posicion impar

[2, 4, 6]

In [25]:
L[::2]#acceder de dos en dos, en posicion par

[1, 3, 5]

In [26]:
L[-1]#Ultimo elemento

6

In [29]:
8 in L # preguntar si 8 esta en L y devuelve un valor booleano

False

In [30]:
L.append(23)

# BUCLES

## FOR

Iteran sobre una colección(string, lista)
Conoces la cantidad de ciclos

In [33]:
for numero in L:
    print(numero)

1
2
3
4
5
6
23


In [34]:
nombre = "Jhon Cruz"
for c in nombre:
    print(c)

J
h
o
n
 
C
r
u
z


In [32]:
for x in range(0,10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [1]:
notas = [4,4.5,3.2,1,2]
suma = 0
for nota in notas:
    suma += nota
    
print(suma/len(notas))

2.94


In [43]:
primos=[2,3,5,7,11,13,17,19]
for idx,p in enumerate(primos):
    print(idx,p)

0 2
1 3
2 5
3 7
4 11
5 13
6 17
7 19


In [44]:
for idx in range(len(primos)):
    print(idx,primos[idx])

0 2
1 3
2 5
3 7
4 11
5 13
6 17
7 19


## While

Se repite hasta que la condicion deje de ser verdadera

In [38]:
count = 0
while(count < 10):
    print("Hola",count)
    count += 1

Hola 0
Hola 1
Hola 2
Hola 3
Hola 4
Hola 5
Hola 6
Hola 7
Hola 8
Hola 9


## Tupla

Colección de datos que no se puede modificar, tamaño y contenido fijo

()

In [49]:
p2 = (1,2)#crear una tupla
p2

(1, 2)

In [2]:
p3 = ("a",1,1.23,"Hola",True)#heterogenea
p3

('a', 1, 1.23, 'Hola', True)

In [51]:
p3[0]#Se accede igual que una lista

'a'

In [52]:
p3[0:2]#llamar un rango de posiciones

('a', 1)

In [53]:
a,b,c,d,e = p3#Guardar Informacion
e

True

In [54]:
l3 = list(p3)#transformar una tupla en lista
l3

['a', 1, 1.23, 'Hola', True]

In [55]:
p5 = tuple(L5)#transformar una lista en tupla
p5

(8, 0, 0, 0, 0, 3.1415, 2, 1)

In [57]:
"Hola que tal estas".split(" ")#para convertir un string en lista

['Hola', 'que', 'tal', 'estas']

In [58]:
"1,2,3,4,5,6,7".split(",")

['1', '2', '3', '4', '5', '6', '7']

## Diccionario

Una coleccion no ordenada de valores: claves

In [59]:
nombre = "Jhon Cruz"
print("Hola %s"%nombre)#ESTO NO

Hola Jhon Cruz


In [3]:
edad = {
    "Jairo":76,#claves string y los valores del tipo que necesite
    "Amparo":56,
    "Jhon":29,
    "Elkin": 22
}

In [61]:
edad["Jairo"]#Se busca por medio de las claves

76

In [62]:
edad["Jairo"]=75#SE LEASIGNA UN VALOR A LA CLAVE JAIRO
edad["Jairo"]

75

In [63]:
edad#PARA MOSTRAR TANO LAS CLAVES COMO LOS VALORES

{'Jairo': 75, 'Amparo': 56, 'Jhon': 29, 'Elkin': 22}

In [64]:
edad.keys()#Devolver claves

dict_keys(['Jairo', 'Amparo', 'Jhon', 'Elkin'])

In [66]:
edad.values()#DEVUELVE VALORES

dict_values([75, 56, 29, 22])

In [67]:
len(edad)#LONGITUD DEL DICCIONARIO

4

In [68]:
"pepe" in edad#buscar la calve

False

In [69]:
"Mario" not in edad#Pregunta contraria

True

In [4]:
del edad["Jairo"]#Borrar la clave
edad

{'Amparo': 56, 'Jhon': 29, 'Elkin': 22}

In [6]:
del edad

NameError: name 'edad' is not defined

## NUMPY #####(Numpay)

Libreria python para manejo de numeros, matrices

In [72]:
import numpy as np
from numpy import *

In [74]:
l1 = [1,2,3,4,5,6,7,8]
x1 = np.array(l1)#CONVERTIR LA LISTA EN UN ARREGLO
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
x2 = np.array(l1,dtype='complex_')#PARA CONVERTIR EL ARREGLO EN COMPLEJO
x2

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j])

In [78]:
np.zeros((3,4))#3filas 3 columnas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
np.ones((3,4))#3 filas y 3 columnas

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
np.arange(10)#array de 0 a 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.arange(3,12,dtype=np.float)#array de 3 a 12 de tipo float

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [82]:
np.arange(4,5,0.1)#array intervalo de 4 a 5 en intervalos de 0.1

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [84]:
np.linspace(1,7,12)# crea valores del 1 al 7 en 12 parte

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [85]:
np.eye(5)#matrix de 5x5 donde su diagonal es uno

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [90]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [91]:
x.reshape((6,4))#Multiplos

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [92]:
x = np.array([[1,2,3],[4,5,6]])#2 FILAS 3 COLUMNAS
x

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np.ravel(x)#aplanar ese array datos, modifica el original

array([1, 2, 3, 4, 5, 6])

In [97]:
x.flatten()#copia de ese array aplanado

array([1, 2, 3, 4, 5, 6])

In [99]:
np.transpose(x)#Cambiar filas por columnas

array([[1, 4],
       [2, 5],
       [3, 6]])

In [100]:
np.resize(x,(3,5))#el arreglo y la forma en que lo quiere distribuir, si hace falta empieza a rellenar de nuevo

array([[1, 2, 3, 4, 5],
       [6, 1, 2, 3, 4],
       [5, 6, 1, 2, 3]])

## Propiedades de los Arreglos

In [103]:
x = np.arange(12)
x = x.reshape((3,4))#volver el arreglo en 3 filas y 4 columnas
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
x.ndim#La dimension d ela matriz

2

In [105]:
x.shape#cantidad de filas y columnas

(3, 4)

In [106]:
x.size#numero de elementos en la matriz

12

In [109]:
x[2]#te muestra la fila 2

array([ 8,  9, 10, 11])

In [111]:
x[2,1]#para buscar una posicion exacta

9

In [112]:
x.shape = (4,3)#Redimensional el array
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [114]:
x[1:3,0:2]# de la fila 1 a la 3, y de la columna 0 a la 2

array([[3, 4],
       [6, 7]])

In [115]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [116]:
y[3:6]#PARA VSUALIZAR UN RANGO ESPECIFICO DEL ARRAY

array([3, 4, 5])

In [117]:
y[1:7:2]#UN RANGO ESPECIFICO Y DE DOS EN DOS

array([1, 3, 5])

In [118]:
z = np.arange(10,6,-1)#UN RANGO ESPECIFICO PERO EN MENOS SALTOS
z

array([10,  9,  8,  7])

In [119]:
x=np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [120]:
x[x>30]#Numeros mayores a 30

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [121]:
cond = x < 25 # guardar las condiciones
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [122]:
x[12:24]=1# modificar las posiciones
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [124]:
x[13:16]=[6,9,12]#Guardar datos en posiciones
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Copias de Arreglos

In [125]:
x = np.arange(10)#asignacion arreglo

In [126]:
y = x # No estamos generando una copia

In [130]:
y.shape=(2,5)#CAMBIAR LA DIMENSION POR 2 FILAS Y 5 COLUMNAS
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [131]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [141]:
z = x.copy()#una copia 
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [143]:
z.shape=(10,1)#CAMBIAR LAS DIMENSIONES
z

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [144]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [135]:
t = x.view()#vista, comparte la informacion pero no tienen las mismas propiedades
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [140]:
t.shape = (5,2)#CAMBIAR DIMENSIONES
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [145]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [147]:
s = x[0:2,1:3]#esto es una vista
s

array([[1, 2],
       [6, 7]])

## Funciones Universales -> ufunc

In [150]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
x+3#incluye resta,multiplicacion, division

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [154]:
alpha = np.linspace(0,2*np.pi,4)#crear un array entre o y 2pi de 4 datos
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [156]:
np.cos(alpha)#de cada uno

array([ 1. , -0.5, -0.5,  1. ])

In [157]:
np.exp(x)#e a la algo de cada posicion

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [158]:
np.power(3,x)#potencia a la 3 de cada posicion

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

In [159]:
np.sum(x)#suma de todo el array

45

In [160]:
np.nansum(x)#elimina los posisbles nan

45

In [161]:
np.prod(x)#elproducto

0

In [162]:
np.mean(x)#La media

4.5

In [165]:
np.min(x)#dato menor

0

In [166]:
np.max(x)#dato mayor

9

In [168]:
np.std(x)#desviacion tipica

2.8722813232690143

In [169]:
np.var(x)# la varianza

8.25

In [170]:
np.argmin(x)#devuelve es el indix del dato menor

0

In [171]:
np.argmax(x)#devuelve es el indix del dato mayor

9

In [172]:
z = np.random.random((3,5))#formar numeros aleatorios
z

array([[0.97651183, 0.18864153, 0.14720447, 0.32912743, 0.3935855 ],
       [0.30488627, 0.78477469, 0.61361998, 0.01481497, 0.86877292],
       [0.11452525, 0.64609789, 0.77382429, 0.89138648, 0.90946583]])

In [173]:
z.sum(axis=0)#suma por columna

array([1.39592336, 1.61951411, 1.53464873, 1.23532889, 2.17182425])

In [174]:
z.sum(axis=1)#suma por fila

array([2.03507077, 2.58686884, 3.33529974])

In [8]:
import numpy as np
xn = np.arange(10)

In [9]:
y = xn

In [13]:
y = y*2

In [14]:
y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
xn

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
yt = xn.reshape(5,2)
yt

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
yx = yt

In [20]:
yx

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
yx[0,0]=5

In [22]:
yx

array([[5, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
yt

array([[5, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])